apiVersion: v1
kind: Config

clusters:
  - cluster:
      proxy-url: http://proxy.example.org:3128
      server: https://k8s.example.org/k8s/clusters/c-xxyyzz
    name: duchy

users:
  - name: duchy-user

contexts:
  - context:
    name: duchy-user@duchy