name: Create Secrets

on:
  push:
    branches: [ "terraform-duchy" ]

jobs:
  push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Clone the repositories
      - name: Clone repositories
        run: |
          cd /tmp
          echo "Cloning the cross-media-measurement repository"
          git clone -b main https://github.com/world-federation-of-advertisers/cross-media-measurement.git
          cd cross-media-measurement

      - name: copying generic secrets for testing
        working-directory: /tmp/cross-media-measurement
        run: |
          mkdir k8s-secrets
          cd /src/main/k8s/testing/secretfiles
          # cp duchy_cert_config.textproto > .



