name: Create Secrets

on:
  push:
    branches: [ "terraform-duchy" ]

jobs:
  push_docker_image:
    runs-on: 20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

   #  - name: Creating all_root_certs.pem
    #    run: |
          cat *_root.pem > all_root_certs.pem

    #  - name: Copy certs from secrets directory
    #    run: |


