name: Create Secrets

on:
  push:
    branches: [ "terraform-duchy" ]

jobs:
  push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Clone the repositories
      - name: Clone repositories
        run: |
          cd /tmp
          echo "Cloning the cross-media-measurement repository"
          git clone -b main https://github.com/world-federation-of-advertisers/cross-media-measurement.git
          cd cross-media-measurement

      - name: copying generic secrets for testing
        working-directory: /tmp/cross-media-measurement
        run: |
          mkdir k8s-secrets
          cp src/main/k8s/testing/secretfiles/worker1_tls.pem /tmp/cross-media-measurement/k8s-secrets
          ls k8s-secrets

      - name: copying generic secrets for testing
        working-directory: /tmp/cross-media-measurement
        run: |
          cp src/main/k8s/testing/secretfiles/aggregator_protocols_setup_config.textproto /tmp/cross-media-measurement/k8s-secrets
          ls k8s-secrets      



