name: Create Secrets

on:
  push:
    branches: [ "terraform-duchy" ]

jobs:
  push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Creating a directory for saving secrets
        run: |
          mkdir k8s-secrets
          cd k8s-secrets

      - name: copying generic secrets for testing
        working-directory: k8s-secrets
        run: cp /src/main/k8s/testing/secretfiles/duchy_cert_config.textproto .



