name: Create Secrets

on:
  push:
    branches: [ "terraform-duchy" ]

jobs:
  push_create_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Clone the repositories
      - name: Clone repositories
        run: |
          cd /tmp
          echo "Cloning the cross-media-measurement repository"
          git clone -b main https://github.com/world-federation-of-advertisers/cross-media-measurement.git
          cd cross-media-measurement

      - name: copying worker1_tls.pem secrets for testing
        working-directory: /tmp/cross-media-measurement
        run: |
          mkdir k8s-secrets
          cp src/main/k8s/testing/secretfiles/worker1_tls.pem /tmp/cross-media-measurement/k8s-secrets
          ls k8s-secrets

      - name: copying aggregator_protocols_setup_config.textproto secrets for testing
        working-directory: /tmp/cross-media-measurement
        run: |
          cp src/main/k8s/testing/secretfiles/aggregator_protocols_setup_config.textproto /tmp/cross-media-measurement/k8s-secrets
          ls k8s-secrets      

      - name: copying duchy_cert_config.textproto secrets for testing
        working-directory: /tmp/cross-media-measurement
        run: |
          cp src/main/k8s/testing/secretfiles/duchy_cert_config.textproto /tmp/cross-media-measurement/k8s-secrets
          ls k8s-secrets  

      - name: copying worker1_cs_cert.der secrets for testing
        working-directory: /tmp/cross-media-measurement
        run: |
          cp src/main/k8s/testing/secretfiles/worker1_cs_cert.der /tmp/cross-media-measurement/k8s-secrets
          ls k8s-secrets  

      - name: copying worker1_cs_private.der secrets for testing
        working-directory: /tmp/cross-media-measurement
        run: |
          cp src/main/k8s/testing/secretfiles/worker1_cs_private.der /tmp/cross-media-measurement/k8s-secrets
          ls k8s-secrets  

      - name: copying worker1_tls.key secrets for testing
        working-directory: /tmp/cross-media-measurement
        run: |
          cp src/main/k8s/testing/secretfiles/worker1_tls.key /tmp/cross-media-measurement/k8s-secrets
          ls k8s-secrets            

      - name: Make a yaml file for secret generator
        run:  |
          touch kustomization.yaml
          cat kustomization.yaml
      - name: create all root.pem
        working-directory: /tmp/cross-media-measurement/
        run: |
          find src/main/k8s/testing/secretfiles -name "*_root.pem" -exec cat {} + > all_root_certs.
          ls 

      - name: Import secrets
        working-directory: /tmp/cross-media-measurement/k8s-secrets
        run: |
          touch secrets.yml

      - name: Import content into file
        run: echo "Hello, World!" >> secrets.yml |  
             cat secrets.yml