name: github actor

on:
  push:
    branches: [ "terraform-duchy" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print GitHub actor
        run: echo "The GitHub actor is ${{ github.actor }}"