name: Generate Certificates and Keys

on:
  push:
    branches: [ "terraform-duchy" ]

jobs:
  generate-certs-secrets:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Clone the repositories
      - name: Clone repositories
        run: |
          cd /tmp
          echo "Cloning the cross-media-measurement repository"
          git clone -b main https://github.com/world-federation-of-advertisers/cross-media-measurement.git
          cd cross-media-measurement

      - name: checking bazel command to create k8s manifest
     #   working-directory: /tmp/cross-media-measurement
        run: |
          bazelisk run //duchy:apply_kustomization 
          kubectl config set-cluster dev-halo-duchy-worker
          
