name: Push Docker Image to Github Artifacts

on:
  push:
    branches: [ "terraform-duchy" ]

jobs:
  push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Clone the repositories
      - name: Clone repositories
        run: |
          cd /tmp
          echo "Cloning the cross-media-measurement repository"
          git clone -b main https://github.com/world-federation-of-advertisers/cross-media-measurement.git
          cd cross-media-measurement

      - name: Build and push Docker image
        working-directory: /tmp/cross-media-measurement
        env:
          IMAGE_NAME: halo-cmm-sandbox/push_duchy:build-0001
        run: |
          bazel query 'filter("push_duchy", kind("container_push", //src/main/docker:all))' |
          xargs bazel build -c opt --define container_registry=ghcr.io \
          --define image_repo_prefix=halo-cmm-sandbox --platforms=//build/platforms:ubuntu_20_04_rbe --define image_tag=build-0001
          docker buildx build --platform linux/amd64,linux/arm64 --push --tag ${{ env.IMAGE_NAME }} .

      - name: Upload Docker image to Github Artifacts
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: wfa-hkawalkar
          password: ${{ secrets.GITHUB_TOKEN }