# Copyright 2023 The Cross-Media Measurement Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Configure Duchy

on:
  #workflow_call:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Image tag needed for configuration"
        type: string
        required: true
      duchy_name:
        description: "The name of the Duchy to build"
        required: true
      kubectl_apply:
        description: "Apply the manifest to the cluster"
        required: false
        type: boolean

env:
  REGISTRY: ghcr.io
  REPO_PREFIX: world-federation-of-advertisers/packages
jobs:
  create_k8s_manifest:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Clone the repositories
      - name: Clone repositories
        run: |
          cd /tmp
          echo "Cloning the cross-media-measurement repository"
          git clone -b main https://github.com/world-federation-of-advertisers/cross-media-measurement.git
          cd /tmp/cross-media-measurement

      # TODO(wfa-hkawalkar): applying manifest failing.
      - name: Apply secrets
        working-directory: /tmp/cross-media-measurement
        run: bazelisk run //src/main/k8s/testing/secretfiles:apply_kustomization

      # TODO(wfa-hkawalkar): import secrets to manifest from k8s secretsfile.
      # Create k8s manifest
      - name: Build K8s manifest
        working-directory: /tmp/cross-media-measurement
        run: |
          bazelisk build //src/main/k8s/${{ inputs.duchy_name }}_duchy_gke \
          --define k8s_duchy_secret_name=certs-and-configs \
          --define duchy_cert_id=SVVse4xWHL0 \
          --define duchy_storage_bucket=worker1-duchy \
          --define container_registry=${{ env.REGISTRY }} \
          --define image_repo_prefix=${{ env.REPO_PREFIX }} \
          --define image_tag=${{ inputs.image_tag }}

      # Apply manifest
      - name: apply k8s manifest
        if: inputs.kubectl_apply == true
        run: kubectl apply -f bazel-bin/src/main/k8s/dev/worker1_duchy_gke.yaml
